
name: Scala CI

on:
  push:
    branches: [ "main", "cross_spark" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-jdk-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1
    - name: Install Ghostscript
      run: sudo apt-get install ghostscript -y
    - name: Run tests on Spark 3.3.2
      env:
        SPARK_VERSION: 3.3.2
      run: sbt test
    - name: Run tests on Spark 3.4.1
      env:
        SPARK_VERSION: 3.4.1
      run: sbt test
    - name: Run tests on Spark 3.5.0
      env:
        SPARK_VERSION: 3.5.0
      run: sbt test

  build-jdk-17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Install Ghostscript
        run: sudo apt-get install ghostscript -y
      - name: Run tests on Spark 4.0.0
        env:
          SPARK_VERSION: 4.0.0-preview2
          SCALA_VERSION: 2.13.14
        run: sbt test

